package discovery

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

func WriteOutput(dir string, result Result, policy ReviewedPolicy) error {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return err
	}
	result.Normalize()
	files := map[string][]byte{}
	var err error
	files["inventory.yaml"], err = yaml.Marshal(result.Inventory)
	if err != nil {
		return err
	}
	for name, value := range map[string]any{"coverage.json": result.Coverage, "imports.json": result.Imports, "diagnostics.json": result.Diagnostics} {
		files[name], err = json.MarshalIndent(value, "", "  ")
		if err != nil {
			return err
		}
		files[name] = append(files[name], '\n')
	}
	files["imports.tf"] = []byte(renderImports(result.Imports))
	files["terraform.auto.tfvars.json"], err = terraformInputs(result, policy)
	if err != nil {
		return err
	}
	for name, data := range files {
		if err := os.WriteFile(filepath.Join(dir, name), data, 0o640); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
	}
	return nil
}

func renderImports(imports []ImportCandidate) string {
	var b strings.Builder
	b.WriteString("# Generated by cmd/discover. Review before applying.\n")
	for _, item := range imports {
		fmt.Fprintf(&b, "import {\n  to = %s\n  id = %q\n}\n\n", item.TerraformAddress, item.RemoteID)
	}
	return b.String()
}

func terraformInputs(result Result, policy ReviewedPolicy) ([]byte, error) {
	accounts := map[string]any{}
	for name, account := range policy.BillingAccounts {
		projects := map[string]any{}
		for _, project := range result.Inventory.Projects {
			if project.BillingAccountName != name {
				continue
			}
			projects[project.ProjectID] = map[string]any{
				"project_number":      project.ProjectNumber,
				"classification":      project.Classification,
				"protected_reason":    project.Reason,
				"monthly_amount":      project.MonthlyAmount,
				"currency_code":       project.CurrencyCode,
				"budget_display_name": project.CanonicalDisplayName,
			}
		}
		accounts[name] = map[string]any{"default_monthly_amount": account.DefaultMonthlyAmount, "currency_code": account.CurrencyCode, "projects": projects}
	}
	data, err := json.MarshalIndent(map[string]any{"organization_id": strings.TrimPrefix(result.Inventory.Organization, "organizations/"), "control_project_id": policy.ControlProjectID, "billing_accounts": accounts}, "", "  ")
	return append(data, '\n'), err
}
